### ISSUE TITLE
你好，我下载项目之后，运行之后，cmd显示 [ event ] build page: /next/dist/pages/_error

### ISSUE THREAD

**Issue by wangxxxb** [code-coder/next-mobile-complete-app#2]
![Snipaste_2019-10-21_17-08-14](https://user-images.githubusercontent.com/34377716/67192052-6b240200-f425-11e9-8efb-00619c2a182c.png)

**Comment by wangxxxb** [comment]
谢谢了

**Comment by zhanglin-doudou** [comment]
之前做的时候用的7.几的版本做的
